export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-container-low': 'var(--color-surface-container-low)',
        tertiary: 'var(--color-tertiary)',
        'on-surface': 'var(--color-on-surface)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'inverse-surface': 'var(--color-inverse-surface)',
        error: 'var(--color-error)',
        'primary-dim': 'var(--color-primary-dim)',
        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-background': 'var(--color-on-background)',
        surface: 'var(--color-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-primary': 'var(--color-on-primary)',
        'on-error-container': 'var(--color-on-error-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-tint': 'var(--color-surface-tint)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'error-container': 'var(--color-error-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        outline: 'var(--color-outline)',
        'on-error': 'var(--color-on-error)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'error-dim': 'var(--color-error-dim)',
        background: 'var(--color-background)',
        'secondary-container': 'var(--color-secondary-container)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        secondary: 'var(--color-secondary)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
