version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 8 1,15 * *'
    assignees:
      - 'mkobit'
    cooldown:
      default-days: 14
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 8 1,15 * *'
    assignees:
      - 'mkobit'
    cooldown:
      default-days: 14
    groups:
      all:
        patterns:
          - "*"
