import { describe, expect, test } from 'bun:test';
import fs from 'node:fs';
import path from 'node:path';
import { CANOPY_WIT_SPECIFICATION, GRAPHQL_SDL_SCHEMA, PROTO_SERVICES_SDL } from '../src';

describe('Schema Baseline Snapshots', () => {
  const baselinesDir = path.resolve(__dirname, '../schema-baselines');

  test('baseline snapshot files exist and match current exports', () => {
    const gqlPath = path.join(baselinesDir, 'graphql.graphql');
    const protoPath = path.join(baselinesDir, 'connect.proto');
    const witPath = path.join(baselinesDir, 'plugin.wit');
    const schemaPath = path.join(baselinesDir, 'approved-breaking-changes.schema.json');
    const waiverPath = path.join(baselinesDir, 'approved-breaking-changes.json');

    expect(fs.existsSync(gqlPath)).toBe(true);
    expect(fs.existsSync(protoPath)).toBe(true);
    expect(fs.existsSync(witPath)).toBe(true);
    expect(fs.existsSync(schemaPath)).toBe(true);
    expect(fs.existsSync(waiverPath)).toBe(true);

    const gqlContent = fs.readFileSync(gqlPath, 'utf8');
    expect(gqlContent).toContain('AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY');
    expect(gqlContent).toContain('type Query');
    expect(gqlContent).toContain(GRAPHQL_SDL_SCHEMA.trim());

    const protoContent = fs.readFileSync(protoPath, 'utf8');
    expect(protoContent).toContain('AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY');
    expect(protoContent).toContain('syntax = "proto3";');
    expect(protoContent).toContain(PROTO_SERVICES_SDL.trim());

    const witContent = fs.readFileSync(witPath, 'utf8');
    expect(witContent).toContain('AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY');
    expect(witContent).toContain('package canopy:graph-api@0.1.0;');
    expect(witContent).toContain(CANOPY_WIT_SPECIFICATION.trim());

    const waiverContent = JSON.parse(fs.readFileSync(waiverPath, 'utf8')) as {
      readonly waivers: readonly unknown[];
    };
    expect(waiverContent.waivers).toEqual([]);
  });
});
