import { parseArgs } from 'node:util';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { checkApiCompatibility, Waiver } from './lib/api-compatibility-checker.js';
import { GRAPHQL_SDL_SCHEMA, PROTO_SERVICES_SDL, CANOPY_WIT_SPECIFICATION } from '../packages/api-adapter/src/index.js';

const { values } = parseArgs({
  options: {
    target: { type: 'string', default: 'all' },
    'update-baselines': { type: 'boolean', default: false },
    'allow-breaking': { type: 'boolean', default: false },
    'add-waiver': { type: 'boolean', default: false },
    protocol: { type: 'string' },
    path: { type: 'string' },
    reason: { type: 'string' },
    ticket: { type: 'string' },
    'expires-at': { type: 'string' },
    'change-type': { type: 'string' },
  },
  strict: false,
});

const BASELINES_DIR = path.resolve(
  process.cwd(),
  'packages/api-adapter/schema-baselines',
);
const WAIVERS_FILE = path.join(BASELINES_DIR, 'approved-breaking-changes.json');

// Read waivers
let waiversData = { waivers: [] as Waiver[] };
if (fs.existsSync(WAIVERS_FILE)) {
  const content = fs.readFileSync(WAIVERS_FILE, 'utf-8');
  waiversData = JSON.parse(content);
}

if (values['add-waiver']) {
  const expiresAtDefault = new Date();
  expiresAtDefault.setDate(expiresAtDefault.getDate() + 90);

  const newWaiver: Waiver = {
    id: crypto.randomUUID(),
    protocol: (values.protocol as any) || 'all',
    path: values.path || 'unknown',
    changeType: values['change-type'] || 'UNKNOWN',
    reason: values.reason || 'No reason provided',
    author: process.env.USER || 'unknown',
    expiresAt: values['expires-at'] || expiresAtDefault.toISOString().split('T')[0],
    ticket: values.ticket || 'UNKNOWN-TICKET',
  };

  waiversData.waivers.push(newWaiver);
  fs.writeFileSync(WAIVERS_FILE, JSON.stringify(waiversData, null, 2) + '\n');
  console.log(`✅ Added waiver for ${newWaiver.path} (${newWaiver.protocol})`);
  process.exit(0);
}

const target = values.target as 'graphql' | 'connect' | 'wit' | 'all';

const result = checkApiCompatibility({
  target,
  overrideWaivers: waiversData.waivers,
});

if (values['update-baselines']) {
  if (!result.success && !values['allow-breaking']) {
    console.error('ERROR: Unapproved breaking changes exist. Use --allow-breaking to override or add waivers first.');
    console.error(result.formattedDiagnostic);
    process.exit(1);
  }

  // Regenerate baseline files with autogenerated header banners
  const banner = `/* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY */\n`;
  if (target === 'all' || target === 'graphql') {
    fs.writeFileSync(path.join(BASELINES_DIR, 'graphql.graphql'), banner + GRAPHQL_SDL_SCHEMA.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  if (target === 'all' || target === 'connect') {
    fs.writeFileSync(path.join(BASELINES_DIR, 'connect.proto'), banner + PROTO_SERVICES_SDL.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  if (target === 'all' || target === 'wit') {
    fs.writeFileSync(path.join(BASELINES_DIR, 'plugin.wit'), banner + CANOPY_WIT_SPECIFICATION.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  console.log('✅ Baselines updated successfully.');
  process.exit(0);
}

if (result.success) {
  console.log('✅ All API compatibility checks passed across GraphQL, Connect Protobuf, and WASM WIT.');
  process.exit(0);
} else {
  console.error(result.formattedDiagnostic);
  process.exit(1);
}
