import { parseArgs } from 'node:util';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { checkApiCompatibility, Waiver } from './lib/api-compatibility-checker.js';

const { values } = parseArgs({
  options: {
    target: { type: 'string', default: 'all' },
    'update-baselines': { type: 'boolean', default: false },
    'allow-breaking': { type: 'boolean', default: false },
    'add-waiver': { type: 'boolean', default: false },
    protocol: { type: 'string' },
    path: { type: 'string' },
    reason: { type: 'string' },
    ticket: { type: 'string' },
    'expires-at': { type: 'string' },
    'change-type': { type: 'string' },
  },
  strict: false,
});

const BASELINES_DIR = path.resolve(
  process.cwd(),
  'packages/api-adapter/schema-baselines',
);
const WAIVERS_FILE = path.join(BASELINES_DIR, 'approved-breaking-changes.json');

// Read waivers
let waiversData = { waivers: [] as Waiver[] };
if (fs.existsSync(WAIVERS_FILE)) {
  const content = fs.readFileSync(WAIVERS_FILE, 'utf-8');
  waiversData = JSON.parse(content);
}

if (values['add-waiver']) {
  const expiresAtDefault = new Date();
  expiresAtDefault.setDate(expiresAtDefault.getDate() + 90);

  const newWaiver: Waiver = {
    id: crypto.randomUUID(),
    protocol: (values.protocol as any) || 'all',
    path: values.path || 'unknown',
    changeType: values['change-type'] || 'UNKNOWN',
    reason: values.reason || 'No reason provided',
    author: process.env.USER || 'unknown',
    expiresAt: values['expires-at'] || expiresAtDefault.toISOString().split('T')[0],
    ticket: values.ticket || 'UNKNOWN-TICKET',
  };

  waiversData.waivers.push(newWaiver);
  fs.writeFileSync(WAIVERS_FILE, JSON.stringify(waiversData, null, 2) + '\n');
  console.log(`✅ Added waiver for ${newWaiver.path} (${newWaiver.protocol})`);
  process.exit(0);
}

const overrideGql = fs.existsSync(path.join(BASELINES_DIR, 'graphql.graphql')) 
  ? fs.readFileSync(path.join(BASELINES_DIR, 'graphql.graphql'), 'utf-8') : undefined;

const overrideProto = fs.existsSync(path.join(BASELINES_DIR, 'connect.proto'))
  ? fs.readFileSync(path.join(BASELINES_DIR, 'connect.proto'), 'utf-8') : undefined;

const overrideWit = fs.existsSync(path.join(BASELINES_DIR, 'plugin.wit'))
  ? fs.readFileSync(path.join(BASELINES_DIR, 'plugin.wit'), 'utf-8') : undefined;

const result = checkApiCompatibility({
  overrideGql,
  overrideProto,
  overrideWit,
  overrideWaivers: waiversData.waivers,
});

if (values['update-baselines']) {
  if (!result.success && !values['allow-breaking']) {
    console.error(result.formattedDiagnostic);
    process.exit(1);
  }

  // Regenerate baseline files with autogenerated header banners
  const banner = `/* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY */\n`;
  if (overrideGql) {
    fs.writeFileSync(path.join(BASELINES_DIR, 'graphql.graphql'), banner + overrideGql.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  if (overrideProto) {
    fs.writeFileSync(path.join(BASELINES_DIR, 'connect.proto'), banner + overrideProto.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  if (overrideWit) {
    fs.writeFileSync(path.join(BASELINES_DIR, 'plugin.wit'), banner + overrideWit.replace(/\/\* AUTOGENERATED HEADER - DO NOT EDIT DIRECTLY \*\/\n/g, ''));
  }
  console.log('✅ Baselines updated successfully.');
  process.exit(0);
}

if (result.success) {
  console.log('✅ All API compatibility checks passed across GraphQL, Connect Protobuf, and WASM WIT.');
  process.exit(0);
} else {
  console.error(result.formattedDiagnostic);
  process.exit(1);
}
