/* eslint-disable unicorn/no-process-exit, no-console, no-restricted-globals, import/extensions -- CLI script */
import { parseArgs } from 'node:util';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { checkApiCompatibility, type Waiver } from './lib/api-compatibility-checker.js';
import {
  GRAPHQL_SDL_SCHEMA,
  PROTO_SERVICES_SDL,
  CANOPY_WIT_SPECIFICATION,
} from '../packages/api-adapter/src/index.js';

const { values } = parseArgs({
  options: {
    target: { type: 'string', default: 'all' },
    'update-baselines': { type: 'boolean', default: false },
    'allow-breaking': { type: 'boolean', default: false },
    'add-waiver': { type: 'boolean', default: false },
    protocol: { type: 'string' },
    path: { type: 'string' },
    reason: { type: 'string' },
    ticket: { type: 'string' },
    'expires-at': { type: 'string' },
    'change-type': { type: 'string' },
  },
  strict: false,
});

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const BASELINES_DIR = path.resolve(__dirname, '../packages/api-adapter/schema-baselines');
const WAIVERS_FILE = path.join(BASELINES_DIR, 'approved-breaking-changes.json');

const waiversData = fs.existsSync(WAIVERS_FILE)
  ? (JSON.parse(fs.readFileSync(WAIVERS_FILE, 'utf8')) as { waivers: Waiver[] })
  : { waivers: [] as Waiver[] };

if (values['add-waiver']) {
  const expiresAtDefault = new Date();
  expiresAtDefault.setDate(expiresAtDefault.getDate() + 90);

  const newWaiver: Waiver = {
    id: crypto.randomUUID(),
    protocol: (values.protocol as 'graphql' | 'connect' | 'wit' | 'all' | undefined) || 'all',
    path: values.path || 'unknown',
    changeType: values['change-type'] || 'UNKNOWN',
    reason: values.reason || 'No reason provided',
    author: process.env.USER || 'unknown',
    expiresAt: values['expires-at'] || expiresAtDefault.toISOString().split('T', 1)[0] || '',
    ticket: values.ticket || 'UNKNOWN-TICKET',
  };

  const newWaiversData = { waivers: [...waiversData.waivers, newWaiver] };
  fs.writeFileSync(WAIVERS_FILE, JSON.stringify(newWaiversData, null, 2) + '\n');
  console.log(`✅ Added waiver for ${newWaiver.path} (${newWaiver.protocol})`);
  process.exit(0);
}

const target = values.target as 'graphql' | 'connect' | 'wit' | 'all';

const result = checkApiCompatibility({
  target,
  overrideWaivers: waiversData.waivers,
});

if (values['update-baselines']) {
  if (!result.success && !values['allow-breaking']) {
    console.error(
      'ERROR: Unapproved breaking changes exist. Use --allow-breaking to override or add waivers first.',
    );
    console.error(result.formattedDiagnostic);
    process.exit(1);
  }

  // Regenerate baseline files with autogenerated header banners
  const banner = `/* AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY */\n`;
  if (target === 'all' || target === 'graphql') {
    fs.writeFileSync(
      path.join(BASELINES_DIR, 'graphql.graphql'),
      banner +
        GRAPHQL_SDL_SCHEMA.replaceAll('/* AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY */\n', ''),
    );
  }
  if (target === 'all' || target === 'connect') {
    fs.writeFileSync(
      path.join(BASELINES_DIR, 'connect.proto'),
      banner +
        PROTO_SERVICES_SDL.replaceAll('/* AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY */\n', ''),
    );
  }
  if (target === 'all' || target === 'wit') {
    fs.writeFileSync(
      path.join(BASELINES_DIR, 'plugin.wit'),
      banner +
        CANOPY_WIT_SPECIFICATION.replaceAll(
          '/* AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY */\n',
          '',
        ),
    );
  }
  console.log('✅ Baselines updated successfully.');
  process.exit(0);
}

if (result.success) {
  console.log(
    '✅ All API compatibility checks passed across GraphQL, Connect Protobuf, and WASM WIT.',
  );
  process.exit(0);
} else {
  console.error(result.formattedDiagnostic);
  process.exit(1);
}
