import { describe, expect, test } from 'bun:test';
import fs from 'node:fs';
import path from 'node:path';
import { CANOPY_WIT_SPECIFICATION } from '../src';

describe('Plugin host schema baseline', () => {
  test('the inline WIT baseline exists and matches the current export', () => {
    const witPath = path.resolve(__dirname, '../schema-baselines/plugin.wit');
    expect(fs.existsSync(witPath)).toBe(true);
    const witContent = fs.readFileSync(witPath, 'utf8');
    expect(witContent).toContain('AUTOGENERATED BASELINE FILE - DO NOT EDIT MANUALLY');
    expect(witContent).toContain('package canopy:graph-api@0.1.0;');
    expect(witContent).toContain(CANOPY_WIT_SPECIFICATION.trim());
  });
});
